python execute.py --dmgrate 0.0
python execute.py --dmgrate 0.1
python execute.py --dmgrate 0.2
python execute.py --dmgrate 0.3
python execute.py --dmgrate 0.4
python execute.py --dmgrate 0.5
python execute.py --dmgrate 0.6
python execute.py --dmgrate 0.7
python execute.py --dmgrate 0.8
python execute.py --dmgrate 0.9
python execute.py --dmgrate 1.0